#pragma once

#define LP_NO_LAVA_DAMAGE 0
#define LP_TRIPLE_LAVA_DAMAGE 0
#define LP_SKIP_ROBOT_POWERUP 0
#define LP_ALWAYS_BOUNCE 0
#define LP_THIEF_NO_STEAL 0
#define LP_LOBOTOMY 0
#define LP_RESTORE_FUEL_SHIELD 0
#define LP_MAX_ENERGY_RESTORE 100
#define LP_ALWAYS_DROP 0
#define LP_MULTIPLE_DROP 0
#define LP_CRAZY_SPAWN 0
#define LP_ROBOT_GENERATOR_OVERRIDE 0
#define LP_SLOWMOTION 0
#define LP_CLOAKED_ALL 0
#define LP_RAMBO_BOT 0
#define LP_ITEM_INF 1
#define LP_ONE_HIT_KILL 1