#pragma once

#define LP_NO_LAVA_DAMAGE 0
#define LP_TRIPLE_LAVA_DAMAGE 0
#define LP_SKIP_ROBOT_POWERUP 0
#define LP_ALWAYS_BOUNCE 0
#define LP_THIEF_NO_STEAL 1
#define LP_LOBOTOMY 0
#define LP_RESTORE_FUEL_SHIELD 1
#define LP_MAX_ENERGY_RESTORE 200
#define LP_ALWAYS_DROP 1
#define LP_MULTIPLE_DROP 0
#define LP_CRAZY_SPAWN 1